/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ColourVariant {
  'id' : bigint,
  'pantoneCode' : string,
  'hexValue' : string,
  'colourName' : string,
  'fabricId' : bigint,
}
export interface Fabric {
  'id' : bigint,
  'gsm' : number,
  'fabricCode' : string,
  'fabricName' : string,
  'fabricType' : string,
  'imageUrl' : [] | [string],
  'width' : number,
  'composition' : string,
}
export interface _SERVICE {
  'createColourVariant' : ActorMethod<[bigint, string, string, string], bigint>,
  'createFabric' : ActorMethod<
    [string, string, string, string, number, number, [] | [string]],
    bigint
  >,
  'deleteFabric' : ActorMethod<[bigint], undefined>,
  'getAllFabrics' : ActorMethod<[], Array<Fabric>>,
  'getColourVariantsByFabric' : ActorMethod<[bigint], Array<ColourVariant>>,
  'getFabricById' : ActorMethod<[bigint], Fabric>,
  'updateFabric' : ActorMethod<
    [bigint, string, string, string, string, number, number, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];