/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Fabric = IDL.Record({
  'id' : IDL.Nat,
  'gsm' : IDL.Float64,
  'fabricCode' : IDL.Text,
  'fabricName' : IDL.Text,
  'fabricType' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'width' : IDL.Float64,
  'composition' : IDL.Text,
});
export const ColourVariant = IDL.Record({
  'id' : IDL.Nat,
  'pantoneCode' : IDL.Text,
  'hexValue' : IDL.Text,
  'colourName' : IDL.Text,
  'fabricId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createColourVariant' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createFabric' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteFabric' : IDL.Func([IDL.Nat], [], []),
  'getAllFabrics' : IDL.Func([], [IDL.Vec(Fabric)], ['query']),
  'getColourVariantsByFabric' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ColourVariant)],
      [],
    ),
  'getFabricById' : IDL.Func([IDL.Nat], [Fabric], ['query']),
  'updateFabric' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Fabric = IDL.Record({
    'id' : IDL.Nat,
    'gsm' : IDL.Float64,
    'fabricCode' : IDL.Text,
    'fabricName' : IDL.Text,
    'fabricType' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'width' : IDL.Float64,
    'composition' : IDL.Text,
  });
  const ColourVariant = IDL.Record({
    'id' : IDL.Nat,
    'pantoneCode' : IDL.Text,
    'hexValue' : IDL.Text,
    'colourName' : IDL.Text,
    'fabricId' : IDL.Nat,
  });
  
  return IDL.Service({
    'createColourVariant' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createFabric' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteFabric' : IDL.Func([IDL.Nat], [], []),
    'getAllFabrics' : IDL.Func([], [IDL.Vec(Fabric)], ['query']),
    'getColourVariantsByFabric' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ColourVariant)],
        [],
      ),
    'getFabricById' : IDL.Func([IDL.Nat], [Fabric], ['query']),
    'updateFabric' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };