/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Fabric {
    id: bigint;
    gsm: number;
    fabricCode: string;
    fabricName: string;
    fabricType: string;
    imageUrl?: string;
    width: number;
    composition: string;
}
export interface ColourVariant {
    id: bigint;
    pantoneCode: string;
    hexValue: string;
    colourName: string;
    fabricId: bigint;
}
export interface backendInterface {
    createColourVariant(fabricId: bigint, colourName: string, pantoneCode: string, hexValue: string): Promise<bigint>;
    createFabric(fabricCode: string, fabricName: string, fabricType: string, composition: string, gsm: number, width: number, imageUrl: string | null): Promise<bigint>;
    deleteFabric(id: bigint): Promise<void>;
    getAllFabrics(): Promise<Array<Fabric>>;
    getColourVariantsByFabric(fabricId: bigint): Promise<Array<ColourVariant>>;
    getFabricById(id: bigint): Promise<Fabric>;
    updateFabric(id: bigint, fabricCode: string, fabricName: string, fabricType: string, composition: string, gsm: number, width: number, imageUrl: string | null): Promise<void>;
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
    getCallerUserProfile(): Promise<{ name: string } | null>;
    saveCallerUserProfile(profile: { name: string }): Promise<void>;
}
import type { Fabric as _Fabric } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createColourVariant(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createColourVariant(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createColourVariant(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createFabric(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFabric(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFabric(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deleteFabric(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFabric(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFabric(arg0);
            return result;
        }
    }
    async getAllFabrics(): Promise<Array<Fabric>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFabrics();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFabrics();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getColourVariantsByFabric(arg0: bigint): Promise<Array<ColourVariant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getColourVariantsByFabric(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColourVariantsByFabric(arg0);
            return result;
        }
    }
    async getFabricById(arg0: bigint): Promise<Fabric> {
        if (this.processError) {
            try {
                const result = await this.actor.getFabricById(arg0);
                return from_candid_Fabric_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFabricById(arg0);
            return from_candid_Fabric_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFabric(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: number, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFabric(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFabric(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async _initializeAccessControlWithSecret(_secret: string): Promise<void> { return; }
    async getCallerUserProfile(): Promise<{ name: string } | null> { return null; }
    async saveCallerUserProfile(_profile: { name: string }): Promise<void> { return; }
}
function from_candid_Fabric_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fabric): Fabric {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    gsm: number;
    fabricCode: string;
    fabricName: string;
    fabricType: string;
    imageUrl: [] | [string];
    width: number;
    composition: string;
}): {
    id: bigint;
    gsm: number;
    fabricCode: string;
    fabricName: string;
    fabricType: string;
    imageUrl?: string;
    width: number;
    composition: string;
} {
    return {
        id: value.id,
        gsm: value.gsm,
        fabricCode: value.fabricCode,
        fabricName: value.fabricName,
        fabricType: value.fabricType,
        imageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.imageUrl)),
        width: value.width,
        composition: value.composition
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fabric>): Array<Fabric> {
    return value.map((x)=>from_candid_Fabric_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
